package com.example.onlinestore.entities.script.enums;

public enum SubCategory {
    GROCERY, PACKAGED_FOOD, SOAP, DRINKS, WINE, DAIRY, GIFT_ITEMS,
    KIDS_FASHION, LUGGAGE_AND_TRAVEL_GEAR, MENS_FASHION, SHOES_AND_JEWELRY, DESIGNER,
    MOBILE_PHONES_ACCESSORIES, MOBILE_PHONES, TABLET_ACCESSORIES, TABLETS, TELEPHONES_AND_ACCESSORIES,
    TELEVISION, CAMERA, SECURITY_AND_SURVEILLANCE, GADGETS, OUTDOOR_RECREATION, FITNESS_AND_SPORT,BAKERY;
}
